"""GENERATED by the offline router-prompt compiler (t2_bake.py) — do not edit by hand.

The compiled router prompt (dspy-miprov2-seed13), baked to plain strings so the
runtime needs no DSPy. Regenerate by re-running the bake against a new
compile; the golden tests in tests/test_compiled_prompt.py pin this module
to what DSPy actually rendered.
"""

CANDIDATE_ID = 'dspy-miprov2-seed13'
RENDERER_VERSION = 'router-compiled/1'

#: Runtime call config — part of the candidate, not a free choice.
TEMPERATURE = 0.0
MAX_TOKENS = 800

SYSTEM = 'Your input fields are:\n1. `request` (str): the user\'s request, verbatim\nYour output fields are:\n1. `intent` (Literal[\'research\', \'image\', \'archive\', \'minimal\', \'unknown\']):\nAll interactions will be structured in the following way, with the appropriate values filled in.\n\nInputs will have the following structure:\n\n[[ ## request ## ]]\n{request}\n\nOutputs will be a JSON object with the following fields.\n\n{\n  "intent": "{intent}        # note: the value you produce must exactly match (no extra characters) one of: research; image; archive; minimal; unknown"\n}\nIn adhering to this structure, your objective is: \n        Analyze the user request provided below. Based on its content and nature, determine the most appropriate intent from the following categories:\n        - \'research\': The request requires detailed analysis, reasoning, or planning.\n        - \'image\': The request includes or references an image (e.g., a file path or screenshot).\n        - \'minimal\': The request is straightforward and requires minimal processing.\n        - \'unknown\': The intent cannot be clearly determined from the request.\n        Respond with only the intent label.'

DEMOS = (
    ('[[ ## request ## ]]\nask lopeteammember codex what to do .. analyse to take the best strategy do not be to much conservative but make the perfect most reliable decision',
     '{\n  "intent": "research"\n}'),
    ('[[ ## request ## ]]\nFor a local SQLite database in rollback-journal mode, same SQLite version and same path, we copy the closed DB file, restore-test the copy with integrity_check, then use it for byte-identical rollback if migration fails. Is that backup mechanism P0/P1 unsafe? Answer briefly and end PASS or NEEDS_FIX.',
     '{\n  "intent": "research"\n}'),
    ('[[ ## request ## ]]\nand maybe in future user will have cli that is not in our list for this reason we need somethink more flexible and dynamic...',
     '{\n  "intent": "unknown"\n}'),
    ('[[ ## request ## ]]\nOkay, please build a sprint. Complete. Completely. Completely sprint. And give me green light when we are ready for implementation.',
     '{\n  "intent": "research"\n}'),
)

USER_PREFIX = '[[ ## request ## ]]\n'
USER_SUFFIX = "\n\nRespond with a JSON object in the following order of fields: `intent` (must be formatted as a valid Python Literal['research', 'image', 'archive', 'minimal', 'unknown'])."


def render(request: str) -> list:
    """The exact message list DSPy's JSONAdapter produced for this program."""
    messages = [{"role": "system", "content": SYSTEM}]
    for user, assistant in DEMOS:
        messages.append({"role": "user", "content": user})
        messages.append({"role": "assistant", "content": assistant})
    messages.append({"role": "user", "content": USER_PREFIX + request + USER_SUFFIX})
    return messages
