"""
Brain dashboard tick — auto-generated index pages.

v0.2 Phase C.7 (stretch). Every 6h, rebuild three Brain pages from
pure filesystem state (no LLM, no FTS, no external deps):

  * Brain/pages/index-journals.md   — last 30 days, one bullet each
  * Brain/pages/index-pages.md      — every page grouped by letter
  * Brain/pages/index-god-nodes.md  — top-25 wikilinks by incoming count

Writes are atomic (tmp + rename). Every page is tagged with a
[[sancho]] + [[brain-dashboard]] footer so Sebastian can reverse-link
find which tick produced it.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import Counter
from datetime import datetime, timezone, timedelta
from pathlib import Path


def _makakoo_home() -> Path:
    home = os.environ.get("MAKAKOO_HOME") or os.environ.get("HARVEY_HOME")
    if home:
        return Path(home)
    return Path.home() / "MAKAKOO"


WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")
FOOTER = "- _Auto-generated by [[SANCHO]] [[brain_dashboard]]. Regenerated every 6h._"


def _atomic_write(path: Path, body: str) -> None:
    tmp = path.with_suffix(".md.tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(path)


def _build_index_journals(home: Path) -> str:
    jdir = home / "data" / "Brain" / "journals"
    if not jdir.exists():
        lines = ["- Journal index (no journals yet)"]
        return "\n".join(lines + ["", FOOTER]) + "\n"

    now = datetime.now(timezone.utc).date()
    lines = ["- Journal index — last 30 days"]
    for i in range(30):
        day = now - timedelta(days=i)
        stem = day.strftime("%Y_%m_%d")
        entry = jdir / f"{stem}.md"
        if not entry.exists():
            continue
        try:
            line_count = sum(1 for l in entry.read_text(encoding="utf-8").splitlines() if l.strip())
        except Exception:
            line_count = 0
        iso = day.strftime("%Y-%m-%d")
        lines.append(f"  - [[{iso}]] — {line_count} lines")
    if len(lines) == 1:
        lines.append("  - (no journal entries in the last 30 days)")
    return "\n".join(lines + ["", FOOTER]) + "\n"


def _build_index_pages(home: Path) -> str:
    pdir = home / "data" / "Brain" / "pages"
    if not pdir.exists():
        return "\n".join([
            "- Page index (no pages yet)",
            "",
            FOOTER,
        ]) + "\n"

    names: list[str] = []
    for p in pdir.glob("*.md"):
        stem = p.stem
        # Skip auto-generated dashboards themselves — avoid self-referential bloat.
        if stem.startswith("index-"):
            continue
        names.append(stem)
    names.sort(key=lambda n: n.lower())

    by_letter: "dict[str, list[str]]" = {}
    for n in names:
        first = n[0].upper() if n else "_"
        if not first.isalpha():
            first = "#"
        by_letter.setdefault(first, []).append(n)

    lines = [f"- Page index — {len(names)} pages, {len(by_letter)} letters"]
    for letter in sorted(by_letter):
        lines.append(f"  - {letter}")
        for n in by_letter[letter]:
            lines.append(f"    - [[{n}]]")
    return "\n".join(lines + ["", FOOTER]) + "\n"


def _collect_wikilinks(home: Path) -> Counter:
    counter: Counter = Counter()
    jdir = home / "data" / "Brain" / "journals"
    pdir = home / "data" / "Brain" / "pages"

    for dir_path in (jdir, pdir):
        if not dir_path.exists():
            continue
        for p in dir_path.glob("*.md"):
            try:
                body = p.read_text(encoding="utf-8")
            except Exception:
                continue
            for m in WIKILINK_RE.findall(body):
                counter[m] += 1
    return counter


def _build_index_god_nodes(home: Path) -> str:
    counts = _collect_wikilinks(home)
    # Strip the auto-generated index pages from the ranking — they link
    # to everything and would dominate the list.
    for k in list(counts.keys()):
        if k.startswith("index-"):
            counts.pop(k, None)

    lines = [f"- God nodes — top 25 wikilinks by incoming reference count"]
    if not counts:
        lines.append("  - (no wikilinks yet)")
    else:
        for name, n in counts.most_common(25):
            lines.append(f"  - [[{name}]] × {n}")
    return "\n".join(lines + ["", FOOTER]) + "\n"


def main(argv: "list[str] | None" = None) -> int:
    parser = argparse.ArgumentParser(description="Brain dashboard SANCHO tick.")
    parser.add_argument("--task", default="brain_dashboard", help=argparse.SUPPRESS)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv if argv is not None else None)

    home = _makakoo_home()
    pages_dir = home / "data" / "Brain" / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)

    targets = [
        ("index-journals.md", _build_index_journals(home)),
        ("index-pages.md", _build_index_pages(home)),
        ("index-god-nodes.md", _build_index_god_nodes(home)),
    ]

    if args.dry_run:
        for name, body in targets:
            print(f"would write {pages_dir / name} ({len(body)} bytes)")
        return 0

    for name, body in targets:
        _atomic_write(pages_dir / name, body)
    print(f"brain_dashboard: wrote {len(targets)} index pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
