pub const CORDIS: &str = r#"# Generated by Makakoo OS. AgentSpec remains the source of truth.
# stdout belongs to the JSON-RPC protocol. Do not add a console logger.

- id: sdk-jsonrpc-server
  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'
  config:
    maxTokensAsSuccess: true

- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
    apiKeyEnv: DEEPSEEK_API_KEY
    baseURL: !!js process.env.DEEPSEEK_BASE_URL
    thinking: disabled
    reasoningEffort: off
    models:
      - id: !!js process.env.DSH_MODEL
        name: Makakoo switchAILocal route
        contextWindow: !!js Number(process.env.DSH_CONTEXT_WINDOW ?? 262144)

- id: agent-spine
  name: '@deepseek-ai/dsh-agent-spine-demo'
  config:
    includeHarnessIdentity: false
    includeRuntimeContext: false
    persona: !!js process.env.DSH_SYSTEM_PROMPT
    workspaceContext: false
    skills:
      enabled: false
    toolBash: false
    toolJobs: false

# Deliberately the only model-facing tool source. Makakoo's MCP server
# filters tools/list and gates tools/call using MAKAKOO_AGENT_SLOT.
- id: mcp-makakoo
  name: '@deepseek-ai/dsh-mcp-client'
  config:
    serverName: harvey
    transport: stdio
    command: !!js process.env.MAKAKOO_MCP_BIN ?? 'makakoo-mcp'
    env:
      MAKAKOO_HOME: !!js process.env.MAKAKOO_HOME
      MAKAKOO_AGENT_SLOT: !!js process.env.MAKAKOO_AGENT_SLOT
    failOnStartupError: true
    toolCallTimeoutMs: 60000

- id: sessions
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT
    compression: zstd

- id: session-checkpoints
  name: '@deepseek-ai/dsh-session-checkpoint-policy'

- id: token-meter
  name: '@deepseek-ai/dsh-token-meter'

- id: compaction-basic
  name: '@deepseek-ai/dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    retainRatio: 0.16
    maxTokens: 8192
    compactionRetries: 1
"#;
