/* AUTO-GENERATED. Do not edit by hand.
 *
 * Generates `src/app.ts` for the Flue project. The `app.ts` is
 * the Flue entry point — it registers the LLM provider and
 * mounts the Flue runtime on Hono.
 *
 * Phase 6 of SPRINT-FLUE-DEFAULT-AGENT-SPECS: the LLM provider
 * is chosen at `makakoo agent create` time and passed to the
 * scaffolder as a `DiscoveredProvider`. The scaffolder emits
 * the right `registerProvider` call for each provider type.
 *
 * CRITICAL: non-catalog providers (switchailocal, ollama) default
 * to `contextWindow: 0` and `maxTokens: 0` in Flue v1.0.0-beta.9,
 * which silently limits output to 1 token. We always set both.
 */

use makakoo_core::agents::llm_provider::{DiscoveredProvider, ProviderSource};

/// Render the `src/app.ts` content for the chosen LLM provider.
pub fn render(provider: &DiscoveredProvider) -> String {
    let register_call = register_call(provider);
    format!(
        r#"/* AUTO-GENERATED by `makakoo agent create --specs <PATH>`.
 * Do not edit by hand — re-run makakoo to regenerate.
 *
 * Flue application entry point. Registers the LLM provider and mounts
 * the Flue runtime on Hono. Pattern from the Flue offline docs:
 *   `npx flue docs read guide/models`
 */

import {{ registerProvider }} from '@flue/runtime';
import {{ flue }} from '@flue/runtime/routing';
import {{ Hono }} from 'hono';

{register_call}

const app = new Hono();
app.route('/', flue());

export default app;
"#
    )
}

fn register_call(provider: &DiscoveredProvider) -> String {
    match &provider.source {
        ProviderSource::Local { .. } => register_local(provider),
        ProviderSource::EnvVar { .. } => register_catalog_override(provider),
        ProviderSource::Catalog => register_catalog(provider),
    }
}

fn register_local(provider: &DiscoveredProvider) -> String {
    // Local providers (switchailocal, ollama) need api + baseUrl.
    // The Flue runtime requires contextWindow + maxTokens for
    // non-catalog providers (otherwise output is silently limited
    // to 1 token in v1.0.0-beta.9).
    //
    // Ollama is keyless — but the Flue runtime v1.0.0-beta.9
    // throws "No API key for provider: ollama" when apiKey is empty.
    // Use a non-empty placeholder so the runtime accepts the call;
    // Ollama ignores the key.
    let base_url = provider
        .base_url
        .clone()
        .unwrap_or_else(|| "http://localhost:11434/v1".into());
    let (api_key_var, default_key) = match provider.id.as_str() {
        "switchailocal" => ("AIL_API_KEY", "sk-test-123"),
        _ => ("OLLAMA_API_KEY", "ollama"),  // keyless, placeholder
    };
    format!(
        r#"registerProvider('{id}', {{
  api: '{api}',
  baseUrl: process.env.{base_url_env} ?? '{base_url}',
  apiKey: process.env.{api_key_var} ?? '{default_key}',
  contextWindow: 128_000,
  maxTokens: 8_192,
}});"#,
        id = provider.id,
        api = provider.api_protocol,
        base_url_env = base_url_env_var(&provider.id),
        base_url = base_url,
        api_key_var = api_key_var,
        default_key = default_key,
    )
}

fn register_catalog_override(provider: &DiscoveredProvider) -> String {
    // Cloud providers (anthropic, openai) use the catalog's protocol
    // and metadata. We only need to set the apiKey (and optionally a
    // gateway baseUrl if the user wants to route through a proxy).
    let env_var = match provider.id.as_str() {
        "anthropic" => "ANTHROPIC_API_KEY",
        "openai" => "OPENAI_API_KEY",
        _ => "API_KEY",
    };
    format!(
        r#"registerProvider('{id}', {{
  apiKey: process.env.{env_var},
}});"#,
        id = provider.id,
        env_var = env_var,
    )
}

fn register_catalog(provider: &DiscoveredProvider) -> String {
    // Default fallback: catalog provider with no overrides.
    let env_var = match provider.id.as_str() {
        "anthropic" => "ANTHROPIC_API_KEY",
        "openai" => "OPENAI_API_KEY",
        _ => "API_KEY",
    };
    format!(
        r#"registerProvider('{id}', {{
  apiKey: process.env.{env_var},
}});

# No ANTHROPIC_API_KEY detected — set it before running the agent.
# See docs/agents/spec.md for setup instructions."#,
        id = provider.id,
        env_var = env_var,
    )
}

fn base_url_env_var(provider_id: &str) -> &'static str {
    match provider_id {
        "switchailocal" => "SWITCHAI_BASE_URL",
        "ollama" => "OLLAMA_BASE_URL",
        _ => "LLM_BASE_URL",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use makakoo_core::agents::llm_provider::{DiscoveredProvider, ProviderSource};

    fn make_local(id: &str, model: &str, base_url: &str) -> DiscoveredProvider {
        DiscoveredProvider {
            id: id.into(),
            display_name: id.into(),
            default_model: model.into(),
            source: ProviderSource::Local { base_url: base_url.into() },
            requires_api_key: false,
            base_url: Some(base_url.into()),
            api_protocol: "openai-completions".into(),
        }
    }

    fn make_envvar(id: &str, model: &str, env_var: &str) -> DiscoveredProvider {
        DiscoveredProvider {
            id: id.into(),
            display_name: id.into(),
            default_model: model.into(),
            source: ProviderSource::EnvVar { env_var: env_var.into() },
            requires_api_key: true,
            base_url: None,
            api_protocol: "openai-completions".into(),
        }
    }

    #[test]
    fn render_emits_register_call_and_flue_mount() {
        let p = make_local("switchailocal", "ail-compound", "http://localhost:18080/v1");
        let s = render(&p);
        assert!(s.contains("registerProvider('switchailocal'"));
        assert!(s.contains("flue()"));
        assert!(s.contains("baseUrl: process.env.SWITCHAI_BASE_URL"));
        assert!(s.contains("contextWindow: 128_000"));
        assert!(s.contains("maxTokens: 8_192"));
    }

    #[test]
    fn render_anthropic_uses_envvar() {
        let p = make_envvar("anthropic", "claude-sonnet-4-6", "ANTHROPIC_API_KEY");
        let s = render(&p);
        assert!(s.contains("registerProvider('anthropic'"));
        assert!(s.contains("apiKey: process.env.ANTHROPIC_API_KEY"));
        assert!(!s.contains("contextWindow"));  // catalog provider, no override needed
    }

    #[test]
    fn render_ollama_uses_placeholder_api_key() {
        // Ollama is keyless, but Flue v1.0.0-beta.9 rejects empty apiKey.
        // The scaffolder uses "ollama" as a placeholder so the runtime
        // accepts the call; Ollama ignores the key.
        let p = make_local("ollama", "llama3.1:8b", "http://localhost:11434/v1");
        let s = render(&p);
        assert!(s.contains("registerProvider('ollama'"));
        assert!(s.contains("api: 'openai-completions'"));
        assert!(s.contains("apiKey: process.env.OLLAMA_API_KEY ?? 'ollama'"));
    }
}
