//! `src/agents/assistant.ts` — the agent's main entrypoint.
//! Wires the spec's model + instructions + tools + channels.
//! Triggers are loaded as side-effecting imports at the bottom.

use super::channels;
use super::context::RenderContext;
use super::triggers;

pub fn render(ctx: &RenderContext) -> String {
    let mut s = String::new();

    // Header
    s.push_str("/* AUTO-GENERATED by `makakoo agent create --specs <PATH>`.\n");
    s.push_str(" * Do not edit by hand — re-run makakoo to regenerate.\n");
    s.push_str(" */\n\n");

    // Imports
    s.push_str("import { readFileSync } from 'node:fs';\n");
    s.push_str("import { defineAgent, connectMcpServer } from '@flue/runtime';\n");

    // Channel imports — each channel module exports `tool(id)` and a
    // `channel` runtime object (mounted by the Flue app at startup).
    // Paths are relative to `src/agents/assistant.ts` (this file):
    // `src/channels/X.ts` → `../channels/X.ts`.
    for (i, c) in ctx.spec.channels.iter().enumerate() {
        let var = channels::import_alias(i, c);
        let path = channels::rel_path(i, c);
        let import_path = path.strip_prefix("src/").unwrap_or(&path);
        s.push_str(&format!(
            "import {{ tool as {var}, channel as {var}_channel }} from '../{import_path}';\n",
            var = var,
            import_path = import_path
        ));
    }
    s.push('\n');

    // MCP setup
    s.push_str("// Makakoo's MCP server, exposed over HTTP by `npm run proxy` (mcp-proxy.mjs).\n");
    s.push_str("const mcpUrl = process.env.MAKAKOO_MCP_URL ?? 'http://127.0.0.1:8808/mcp';\n");
    s.push_str("const makakoo = await connectMcpServer('harvey', { url: mcpUrl, transport: 'streamable-http' });\n\n");

    // Tool whitelist
    s.push_str("// Whitelist Makakoo tools per the spec's `tools` list.\n");
    s.push_str("const allowedTools = [\n");
    for tool in &ctx.spec.tools {
        s.push_str(&format!("  '{}',\n", tool));
    }
    s.push_str("];\n");
    s.push_str("const tools = makakoo.tools.filter((t) => allowedTools.includes(t.name));\n\n");

    // Instructions
    s.push_str("const instructions = readFileSync(new URL('../../instructions.txt', import.meta.url), 'utf8');\n\n");

    // Mount the channel runtime objects so the Flue app exposes their
    // webhook routes. The exact registration API is framework-specific
    // (Flue picks them up via static analysis of the agent module).
    s.push_str("// Mount channel ingress routes.\n");
    for (i, _c) in ctx.spec.channels.iter().enumerate() {
        let var = channels::import_alias(i, _c);
        s.push_str(&format!(
            "void {var}_channel; // imported for side effect (route registration)\n",
            var = var
        ));
    }
    s.push('\n');

    // Agent factory
    s.push_str("export default defineAgent(async (ctx) => {\n");
    s.push_str("  const channelTools = [\n");
    for (i, c) in ctx.spec.channels.iter().enumerate() {
        let var = channels::import_alias(i, c);
        s.push_str(&format!("    {var}(ctx.id),\n", var = var));
    }
    s.push_str("  ];\n");
    s.push_str("  return {\n");
    s.push_str(&format!(
        "    model: process.env.AGENT_MODEL ?? '{}',\n",
        ctx.spec.model
    ));
    s.push_str("    instructions,\n");
    s.push_str("    tools: [...tools, ...channelTools],\n");
    s.push_str("  };\n");
    s.push_str("});\n\n");

    // Trigger side-effecting imports — each trigger module starts its
    // own scheduler / HTTP server at module load time. Paths are
    // relative to `src/agents/assistant.ts` (this file):
    // `src/triggers/X.ts` → `../triggers/X.ts`.
    s.push_str("// Triggers (side-effecting imports — each starts its own scheduler / server).\n");
    for (i, t) in ctx.spec.triggers.iter().enumerate() {
        let path = triggers::rel_path(i, t);
        let import_path = path.strip_prefix("src/").unwrap_or(&path);
        s.push_str(&format!(
            "import '../{import_path}';\n",
            import_path = import_path
        ));
    }

    s
}
