"""
GYM Artifact Model — the universal envelope for any input to GYM.

Every artifact that enters GYM (code, skill, agent flow, text, config, prompt)
is wrapped in an ArtifactCandidate. The pipeline is identical for all kinds;
only the handler varies.

Autoreseach model (train.py):
  - Single editable file = train.py
  - val_bpb = single measurable oracle
  - Fixed time budget (5 min)
  - No new packages
  - Simplicity criterion (deletion = win)

GYM generalization:
  - ArtifactCandidate = (path, kind, handler, oracle_score)
  - Handler = typed evaluator (code/skill/agent_flow/text/config/generic)
  - val_bpb equivalent per handler
  - gym improve <path> --goal "..." = the universal intake CLI
"""
from __future__ import annotations
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Literal
import hashlib
import json

# Supported artifact kinds — one handler per kind
ArtifactKind = Literal[
    "code",      # .py .ts .go .rs .js — compile/test/probe oracle
    "skill",     # SKILL.md — meta-harness scenario pass rate
    "agent_flow",# YAML/JSON/MD manifest + handler — replay transcript oracle
    "text",      # .md .txt .prompt — rubric score + compression
    "config",    # .toml .yaml .json — parse/round-trip/dry-run oracle
    "generic",   # unknown — LLM rubric + diff risk gate
]

@dataclass
class ArtifactCandidate:
    """
    Universal artifact envelope for GYM.

    autoreseach equivalent: one train.py file with a single val_bpb score.

    GYM equivalent: one ArtifactCandidate per artifact, scored by a typed handler.
    """
    id: str                      # unique run ID (uuid4 short)
    path: Path                   # git-tracked, single editable file
    kind: ArtifactKind           # determines which handler fires
    goal: str                    # what "improve" means for this artifact

    # Provenance
    git_sha: str = ""            # git commit SHA at intake time
    content_hash: str = ""       # SHA-256 of baseline content

    # Baseline (read-only)
    baseline_content: str = ""   # full file content at intake
    baseline_score: float = 0.0  # oracle score before improvement

    # Candidate (generated by hypothesize layer)
    candidate_content: str = ""  # full replacement content

    # Evaluation
    final_score: float = 0.0    # oracle score after improvement
    val_bpb: float = 0.0         # composite: (final - baseline) / elapsed_sec * 100

    # Hard gates
    hard_failures: list[str] = field(default_factory=list)  # parse fail, test regress, etc.
    risk_warnings: list[str] = field(default_factory=list)

    # Meta
    handler: str = ""            # handler name that produced candidate
    elapsed_seconds: float = 0.0
    source: str = "manual"       # manual | error_funnel | schedule | flag
    source_id: str = ""          # cluster_id / flag_id / etc if applicable

    def __post_init__(self):
        if self.id and not self.git_sha:
            self.git_sha = self._git_sha()
        if self.id and not self.content_hash:
            self.content_hash = self._content_hash()

    def _git_sha(self) -> str:
        try:
            import subprocess
            result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=str(self.path.parent),
                capture_output=True, text=True, timeout=5
            )
            return result.stdout.strip()[:12]
        except Exception:
            return "unknown"

    def _content_hash(self) -> str:
        return hashlib.sha256(self.baseline_content.encode()).hexdigest()[:16]

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "path": str(self.path),
            "kind": self.kind,
            "goal": self.goal,
            "git_sha": self.git_sha,
            "content_hash": self.content_hash,
            "baseline_score": round(self.baseline_score, 4),
            "final_score": round(self.final_score, 4),
            "val_bpb": round(self.val_bpb, 4),
            "hard_failures": self.hard_failures,
            "risk_warnings": self.risk_warnings,
            "handler": self.handler,
            "elapsed_seconds": round(self.elapsed_seconds, 2),
            "source": self.source,
            "source_id": self.source_id,
        }

    @classmethod
    def from_path(cls, path: Path, kind: ArtifactKind, goal: str, source: str = "manual") -> "ArtifactCandidate":
        """Create a candidate from a file path — the gym improve entry point."""
        content = path.read_text()
        candidate_id = hashlib.sha256(f"{path}:{content[:200]}".encode()).hexdigest()[:12]
        return cls(
            id=candidate_id,
            path=path,
            kind=kind,
            goal=goal,
            git_sha="",
            content_hash="",
            baseline_content=content,
            baseline_score=0.0,
            source=source,
        )


@dataclass
class EvaluationResult:
    """Output of a handler's validate() method."""
    baseline_score: float
    candidate_score: float
    hard_failures: list[str]        # must be empty for merge
    evidence: dict                  # handler-specific proof (test output, lint result, etc.)
    simplicity_delta: float = 0.0  # lines added - lines deleted (for tiebreaker)
    risk_warnings: list[str] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return len(self.hard_failures) == 0 and self.candidate_score >= self.baseline_score

    @property
    def val_bpb(self) -> float:
        """Composite score: (score_delta * 100 + simplicity_bonus) / elapsed"""
        bonus = 0.1 if self.simplicity_delta < 0 else max(-0.4, -(self.simplicity_delta / 50) * 0.05)
        return (self.candidate_score - self.baseline_score) + bonus

    def to_dict(self) -> dict:
        return {
            "baseline_score": round(self.baseline_score, 4),
            "candidate_score": round(self.candidate_score, 4),
            "hard_failures": self.hard_failures,
            "passed": self.passed,
            "val_bpb": round(self.val_bpb, 4),
            "simplicity_delta": round(self.simplicity_delta, 4),
            "risk_warnings": self.risk_warnings,
            "evidence_keys": list(self.evidence.keys()),
        }